#端口号
server:
  port: 18883
#配置数据库连接以及数据源
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo
      username: root
      password: 123456
      #连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      #连接等待超时时间
      max-wait: 60000
      #配置连接池在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PsCache,并且指定每个连接上pscahce的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters
      filters: stat,wall
      #spring监控aop切入点
      aop-patterns: com.example.demo.service.*

      #webstatfilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      #statviewservelet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #是否能够重置数据
        reset-enable: false
        #账号，密码访问控制台
        login-username: druid
        login-password: druid123
        #配置白名单，黑名单
      #配置statFilter
      filter:
        stat:
          log-slow-sql: true

