#启动环境
spring:
  profiles:
    active: dev,test
  thymeleaf:
    cache: false
mrbind:
  blog:
    name: mrbind's blog
    title: spring boot
    wholeTitle: ${mrbind.blog.name} -- ${mrbind.blog.title}
